<?xml version="1.0" encoding="utf-8"?><Database Name="admin_Trasua" Class="dbcsdlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=171.244.3.133,1433;Initial Catalog=admin_Trasua;User ID=admin_Trasua" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="admin_TrasuaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbSlide" Member="tbSlides">
    <Type Name="tbSlide">
      <Column Name="slide_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="slide_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="slide_title1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbCityLocation" Member="tbCityLocations">
    <Type Name="tbCityLocation">
      <Column Name="citylocation_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="location_lat" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="location_long" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="location_img" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="location_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="city_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbCollectionImage" Member="tbCollectionImages">
    <Type Name="tbCollectionImage">
      <Column Name="collection_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="collection_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="collection_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="collection_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="collection_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="collection_avatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="collection_youtube" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbCustomer" Member="tbCustomers">
    <Type Name="tbCustomer">
      <Column Name="cus_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cus_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cus_phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cus_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cus_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cus_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cus_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cus_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbCustomerFeedback" Member="tbCustomerFeedbacks">
    <Type Name="tbCustomerFeedback">
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customer_firstname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="customer_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="customer_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbDangKyEmail" Member="tbDangKyEmails">
    <Type Name="tbDangKyEmail">
      <Column Name="dke_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dke_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dke_tinhtrang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbKetNoiMXH" Member="tbKetNoiMXHs">
    <Type Name="tbKetNoiMXH">
      <Column Name="ketnoimxh_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ketnoimxh_facebook" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ketnoimxh_twitter" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ketnoimxh_instagram" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ketnoimxh_google" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbLienHe" Member="tbLienHes">
    <Type Name="tbLienHe">
      <Column Name="lienhe_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lienhe_address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lienhe_phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lienhe_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbOpentime" Member="tbOpentimes">
    <Type Name="tbOpentime">
      <Column Name="open_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="restaurant_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="open_day" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="opentime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbSale" Member="tbSales">
    <Type Name="tbSale">
      <Column Name="sale_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sale_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sale_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sale_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sale_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sale_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sale_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="salecate_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbSaleCate" Member="tbSaleCates">
    <Type Name="tbSaleCate">
      <Column Name="salecate_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="salecate_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="salecate_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbSEO" Member="tbSEOs">
    <Type Name="tbSEO">
      <Column Name="seo_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="seo_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_keyworld" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="page_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.admin_AccessGroupUserForm" Member="admin_AccessGroupUserForms">
    <Type Name="admin_AccessGroupUserForm">
      <Column Name="guf_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="guf_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="form_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_Form_admin_AccessGroupUserForm" Member="admin_Form" ThisKey="form_id" OtherKey="form_id" Type="admin_Form" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserForm" Member="admin_GroupUser" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_GroupUser" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.admin_AccessGroupUserModule" Member="admin_AccessGroupUserModules">
    <Type Name="admin_AccessGroupUserModule">
      <Column Name="gum_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gum_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="module_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserModule" Member="admin_GroupUser" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_GroupUser" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="admin_Module_admin_AccessGroupUserModule" Member="admin_Module" ThisKey="module_id" OtherKey="module_id" Type="admin_Module" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.admin_AccessUserForm" Member="admin_AccessUserForms">
    <Type Name="admin_AccessUserForm">
      <Column Name="uf_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uf_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="username_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="form_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_Form_admin_AccessUserForm" Member="admin_Form" ThisKey="form_id" OtherKey="form_id" Type="admin_Form" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="admin_User_admin_AccessUserForm" Member="admin_User" ThisKey="username_id" OtherKey="username_id" Type="admin_User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.admin_Form" Member="admin_Forms">
    <Type Name="admin_Form">
      <Column Name="form_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="form_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="form_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="form_link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="form_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="module_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_Form_admin_AccessGroupUserForm" Member="admin_AccessGroupUserForms" ThisKey="form_id" OtherKey="form_id" Type="admin_AccessGroupUserForm" />
      <Association Name="admin_Form_admin_AccessUserForm" Member="admin_AccessUserForms" ThisKey="form_id" OtherKey="form_id" Type="admin_AccessUserForm" />
      <Association Name="admin_Module_admin_Form" Member="admin_Module" ThisKey="module_id" OtherKey="module_id" Type="admin_Module" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.admin_GroupUser" Member="admin_GroupUsers">
    <Type Name="admin_GroupUser">
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="groupuser_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="groupuser_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserForm" Member="admin_AccessGroupUserForms" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_AccessGroupUserForm" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserModule" Member="admin_AccessGroupUserModules" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_AccessGroupUserModule" />
      <Association Name="admin_GroupUser_admin_User" Member="admin_Users" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_User" />
    </Type>
  </Table>
  <Table Name="dbo.admin_Module" Member="admin_Modules">
    <Type Name="admin_Module">
      <Column Name="module_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="module_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="module_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="module_icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="module_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="admin_Module_admin_AccessGroupUserModule" Member="admin_AccessGroupUserModules" ThisKey="module_id" OtherKey="module_id" Type="admin_AccessGroupUserModule" />
      <Association Name="admin_Module_admin_Form" Member="admin_Forms" ThisKey="module_id" OtherKey="module_id" Type="admin_Form" />
    </Type>
  </Table>
  <Table Name="dbo.admin_User" Member="admin_Users">
    <Type Name="admin_User">
      <Column Name="username_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username_username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="username_phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_User_admin_AccessUserForm" Member="admin_AccessUserForms" ThisKey="username_id" OtherKey="username_id" Type="admin_AccessUserForm" />
      <Association Name="admin_GroupUser_admin_User" Member="admin_GroupUser" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_GroupUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbNewCate" Member="tbNewCates">
    <Type Name="tbNewCate">
      <Column Name="newcate_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="newcate_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="newcate_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbProduct" Member="tbProducts">
    <Type Name="tbProduct">
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_quantum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_show" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="product_new" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="productcate_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title_web" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="h1_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_cart" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="product_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbProductCate" Member="tbProductCates">
    <Type Name="tbProductCate">
      <Column Name="productcate_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productcate_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="productcate_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productcate_show" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="productgroup_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title_web" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="h1_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productcate_parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="productcate_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbIntroduce" Member="tbIntroduces">
    <Type Name="tbIntroduce">
      <Column Name="introduct_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="introduce_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="introduce_title1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="introduce_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="introduce_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="introduce_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="introduce_dateup" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="introduce_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="seo_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_keyworld" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbNews" Member="tbNews">
    <Type Name="tbNew">
      <Column Name="news_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="news_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="news_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="news_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="news_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="newcate_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="news_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="news_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seo_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbRestaurant" Member="tbRestaurants">
    <Type Name="tbRestaurant">
      <Column Name="restaurant_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="restaurant_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="restaurant_phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="restaurant_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="restaurant_address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="restaurant_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="city_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="restaurant_addressname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="restaurant_map" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="restaurant_map2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="restaurant_linkvideo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="location_lat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="location_long" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="db_owner.tbCity" Member="tbCities">
    <Type Name="tbCity">
      <Column Name="city_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="city_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="city_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="city_show" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="location_lat" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="location_long" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="city_zoom" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>